Repository TNRIS/tnris.org, pull requests merged in 2019-09, with the labels that each got.

#17 Fixing exhibitors on Forum
  templates/events/texas-gis-forum/2019/sponsors.njk
Labels: in progress

#18 Moving New Nav Organization Into Prod
  scss/partials/_home.scss
  scss/partials/_navbar.scss
  scss/partials/_quicknav.scss
  templates/education/nav.njk
  templates/partials/footer.njk
  templates/partials/navbar.njk
Labels: in progress

#26 Updated Agenda Push to Prod
  templates/events/texas-gis-forum/2019/agenda.njk
Labels: in progress

#34 Publishing Justen Keynote Article
  content/markdown/news/2019-09-18-forum-keynote-justen-noakes-heb-director-emergency-preparedness.md
  content/markdown/texas-gis-forum/2019/index.md
  scss/partials/_2019-forum.scss
  scss/partials/_variables.scss
  templates/events/texas-gis-forum/2019/agenda.njk
Labels: in progress

#38 Move miller to silver
  templates/events/texas-gis-forum/2019/sponsors.njk
Labels: In Progress

#37 Publish san Bernard Lidar article
  content/markdown/news/new-usgs-lower-colorado-san-bernard-2018-lidar-data-release.md
Labels: In Progress

#41 adding conrad blucher to exhibitor (push to prod)
  templates/events/texas-gis-forum/2019/sponsors.njk
Labels: Master (Prod)

#44 (reopening) Historical Imagery page changes
  content/markdown/research-distribution-center/historical-imagery-archive.md
  scss/partials/_base.scss
  scss/partials/_rdc.scss
  templates/rdc/rdc-sub.njk
Labels: In Progress

#47 Add announcement to SM contracts
  content/markdown/stratmap/stratmap-contracts.md
  scss/partials/_stratmap.scss
  templates/stratmap/main-content.njk
Labels: Master (Prod), review-in-progress
