Repository TNRIS/tnris.org, pull requests merged in 2020-05, with the labels that each got.

#202 Feature/ed registration buttons
  generate-webpack-config.js
  static/js/training.js
  static/js/training_discount_copy.js
  static/js/training_registration_button.js
  templates/education/education-side.njk
Labels: Enhancement, In Progress, PR-review-in-progress, feature branch, pending

#207 new temporary notice on front page about upcoming online training courses
  package-lock.json
  package.json
  static/js/training_partial.js
  templates/education/education-front.njk
Labels: Content Creation, Develop

#208 Spelling and Broken links
  content/markdown/around-the-state/2015-06-02-usgs-releases-geologic-atlas-of-texas-gat-viewer.md
  content/markdown/around-the-state/2015-10-01-sterling-harris-retires-leaving-gis-legacy-glo.md
  content/markdown/data-catalog/entry/tceq-municipal-solid-waste-sites-and-landfills.md
  content/markdown/geographic-information-office-news/2016-04-20-notes-texas-gis-community-meeting-2nd-quarter-2016.md
  content/markdown/geographic-information-office-news/2016-08-23-notes-texas-gis-community-meeting-3rd-quarter-2016.md
  content/markdown/geographic-information-office-news/2017-01-10-notes-texas-gis-community-meeting-1st-quarter-2017.md
  content/markdown/geographic-information-office-news/2017-04-27-gis-community-meeting-recap-2nd-quarter.md
  content/markdown/geographic-information-office-news/2017-08-24-gis-community-meeting-recap-3rd-quarter.md
  content/markdown/geographic-information-office-news/2018-02-07-east-texas-gis-community-tnris-featured-local-news.md
  content/markdown/geographic-information-office-news/2018-03-08-gis-community-meeting-recap-1st-quarter.md
  content/markdown/geographic-information-office-news/2018-04-17-gis-community-meeting-recap-2nd-quarter.md
  content/markdown/geographic-information-office-news/2019-05-20-gis-community-meeting-slides-2018-3rd-quarter.md
  content/markdown/geographic-information-office-news/2019-08-13-gis-community-meeting-slides-2019-3rd-quarter.md
  content/markdown/geographic-information-office/gis-solutions-group/meeting-notes/2016-07-21-notes-june-2016-dcs-gis-solutions-group.md
  content/markdown/news/2015-07-16-ucgis-fellow-david-cowen-keynote-forum.md
  content/markdown/news/2015-08-03-lidar-data-release-for-georgetown-texas.md
  content/markdown/news/2015-08-11-lidar-data-release-austin-capcog-2012.md
  content/markdown/news/2015-08-24-forum-keynote-ut-professor-todd-humphreys.md
  content/markdown/news/2015-09-25-2015-lidar-data-release-brazos-county.md
  content/markdown/news/2015-10-06-new-brazos-county-city-palestine-aerial-imagery-now-available.md
  content/markdown/news/2015-11-03-forum-thank-you-photo-recap.md
  content/markdown/news/2015-11-05-digging-into-augmented-reality-sandbox.md
  content/markdown/news/2015-11-09-lidar-data-release-middle-brazos-palo-pinto-fema-project.md
  content/markdown/news/2015-11-30-city-of-georgetown-2015-aerial-imagery-now-available.md
  content/markdown/news/2016-03-14-2016-smith-county-aerial-imagery-now-available.md
  content/markdown/news/2016-04-01-h-gac-2008-lidar-data-released-harris-county-surrounding-areas.md
  content/markdown/news/2016-04-05-texas-parks-wildlife-2015-aerial-imagery-now-available.md
  content/markdown/news/2016-04-28-amarillo-dfw-el-paso-lubbock-2015-aerial-imagery-now-available.md
  content/markdown/news/2016-05-27-2016-georodeo-recap-highlights.md
  content/markdown/news/2016-07-26-san-antonio-river-authority-2015-2016-aerial-imagery-now-available.md
  content/markdown/news/2016-10-18-texas-gis-forum-sponsor-spotlight-harris.md
  content/markdown/news/2016-11-04-2016-texas-gis-forum-photo-recap-part-1.md
  content/markdown/news/2017-05-08-new-brazos-2017-aerial-imagery-now-available.md
  content/markdown/news/2017-06-12-tnris-lidar-data-now-available-download.md
  content/markdown/news/2017-09-20-technical-evangelist-technology-advocate-forum-keynote-bern-szukalski.md
  content/markdown/news/2017-11-13-lidar-data-release-east-texas-project.md
  content/markdown/news/2018-01-10-poster-gallery-winners-207-texas-gis-forum.md
  content/markdown/news/2019-06-19-2016-2018-usgs-lidar-releases.md
  content/markdown/research-distribution-center/custom-maps.md
  content/markdown/texas-gis-forum/2015/index.md
  templates/events/georodeo-2019/georodeo-intro.njk
  templates/events/texas-gis-forum/2016/agenda.njk
  templates/events/texas-gis-forum/2016/sponsors.njk
  templates/events/texas-gis-forum/2017/agenda.njk
  templates/events/texas-gis-forum/2018/agenda.njk
  templates/events/texas-gis-forum/2019/agenda.njk
  templates/partials/2014-forum/forum-sponsors.njk
  templates/partials/2015-ortho/statewide-preview.njk
  templates/partials/highlights.njk
  templates/partials/texas-imagery-service/faq-toc.njk
  templates/stratmap/contract-vendors.njk
Labels: Cleanup, Content Creation, PR-review-complete

#211 closes #210
  content/markdown/education/course-cancellations.md
  content/markdown/education/index.md
  content/markdown/education/purchasers.md
  templates/education/education-side.njk
  templates/education/nav.njk
  templates/partials/footer.njk
Labels: Cleanup, Content Creation, re-organization

#209 education page enhancement
  package-lock.json
  static/js/training.js
  static/js/training_discount_copy.js
  templates/education/education-side.njk
  templates/education/main.njk
Labels: Enhancement, feature branch, maintenance

#218 package updates
  package-lock.json
  package.json
Labels: PR-review-in-progress, maintenance
