Repository TNRIS/tnris.org, pull requests merged in 2020-02, with the labels that each got.

#154 Feature/auto pop sgm notes
  generate-webpack-config.js
  static/js/gio_calendar_next_sgm.js
  static/js/gio_solutions_group.js
  templates/gio/gis-solutions-meeting.njk
Labels: Enhancement

#157 package updates
  package-lock.json
  package.json
Labels: dependencies

#160 update lidar spec doc url
  content/markdown/stratmap/elevation-lidar.md
Labels: Master (Prod)

#163 Publish Census Article to prod
  content/markdown/geographic-information-office/index.md
  content/markdown/news/2020-02-13-make-texas-count-2020-census.md
  scss/partials/_base.scss
  templates/gio/gio-sub-dcs.njk
  templates/gio/gio.njk
  templates/news-article.njk
Labels: Master (Prod)

#164 stratmap header condition re-factoring
  templates/stratmap/main.njk
Labels: re-factor
